# Generated by Django 6.1.1 on 2026-10-09 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_citizen_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='YojanaSaathi AI Agent', help_text='Descriptive identifier for this agent key', max_length=120)),
                ('key_prefix', models.CharField(db_index=True, help_text='Public prefix used for key lookup without exposing secret', max_length=16)),
                ('hashed_key', models.CharField(db_index=True, help_text='SHA-256 hash of the complete secret key', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_key_name', models.CharField(blank=True, max_length=120)),
                ('agent_key_prefix', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.CharField(blank=True, max_length=60)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_audit_logs', to='accounts.citizen')),
            ],
            options={
                'verbose_name': 'Agent Audit Log',
                'verbose_name_plural': 'Agent Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenAgentDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegation_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scopes', models.JSONField(default=list, help_text='List of granted scope strings')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_delegations', to='accounts.citizen')),
            ],
            options={
                'verbose_name': 'Citizen Agent Delegation',
                'verbose_name_plural': 'Citizen Agent Delegations',
                'ordering': ['-created_at'],
            },
        ),
    ]
