# Generated by Django 6.1.1 on 2026-10-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='eligibility_rules',
            field=models.JSONField(default=dict),
        ),
    ]
