# Generated by Django 6.1.1 on 2026-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scheme_eligibility_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='application_fields',
            field=models.JSONField(default=list),
        ),
    ]
