# Generated by Django 6.1.1 on 2026-10-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_scheme_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
